bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.shopping_bag, name='shopping_bag'),
    path('add/<item_id>/', views.add_item, name='add_item'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_item, name='remove_item'),
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.PostList.as_view(), name='blog'),
    path("contact", views.contact, name="contact"),
    path('faqs', views.Faqs.as_view(), name='faqs'),
    path('add_post/', views.AddPost, name='add_post'),
    path('update_post/<post_id>', views.update_post, name='update_post'),
    path('delete_post/<post_id>', views.delete_post, name='delete_post'),
    path('sustainable_leather', views.sustainable_leather,
         name='sustainable_leather'),
    path('meet_the_tanner', views.meet_the_tanner, name='meet_the_tanner'),
    path('certs', views.certs, name='certs'),
    path('custom', views.custom, name='custom'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
]

leather_works/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('blog/', include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'leather_works.views.handler404'

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify


class Post(models.Model):
    """
    Main blog post
    """
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts")
    featured_image = models.ImageField(null=True, blank=True, upload_to="images/")
    snippet = models.TextField(max_length=5000, default='Click button to read blog post...')
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title + ' | ' + str(self.author)

    def save(self, *args, **kwargs):
        
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse('blog')


class Contact(models.Model):
    name = models.CharField(max_length=158)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.name




    

blog/forms.py
from django import forms
from django.forms import ModelForm
from .models import Contact, Post


class ContactForm(ModelForm):
    """
    Contact form
    """
    class Meta:
        model = Contact
        fields = '__all__'


# Form for user to create a book review.
class BlogPost(forms.ModelForm):
    """
    Creates a form based on the Post model
    """
    class Meta:
        model = Post
        fields = '__all__'


# Form for user to create a book review.
class CreatePost(forms.ModelForm):
    """
    Creates a form based on the Post model
    """
    class Meta:
        model = Post
        fields = (
            'title',
            'featured_image',
            'snippet', 'content')

    widgets = {
        'title': forms.TextInput(attrs={'class': 'form-control',
                                        'label': 'name'}),
        'feature_image': forms.Select(attrs={'class': 'form-control'}),
        'snippet': forms.Select(attrs={'placeholder': 'snippet of blog'}),
        'content': forms.TextInput(attrs={'placeholder': 'blog post'}),
    }

blog/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.views.generic import ListView, CreateView, View
from .models import Post
from django.contrib.auth.decorators import login_required
from django.utils.text import slugify
from django.http import HttpResponseRedirect
from .forms import ContactForm, BlogPost, CreatePost
from django.contrib import messages


class PostList(ListView):
    """
    Takes the Post Model and makes sure they are
    approved and displayes them on the home page
    """
    model = Post
    template_name = "blog.html"
    paginate_by = 6


class PostDetail(View):
    """
    Gets full post
    """
    def get(self, request, slug, *args, **kwargs):
        queryset = Post.objects
        post = get_object_or_404(queryset, slug=slug)

        return render(
            request,
            "post_details.html",
            {
                "post": post,
            },
        )


@login_required
def update_post(request, post_id):
    """
    Users can update book reviews that they have
    created using a form
    """
    post = Post.objects.get(pk=post_id)
    form = BlogPost(request.POST or None, instance=post)
    if post.author != request.user:
        return redirect('This is not your Post')
    if form.is_valid():
        form.save()
        return HttpResponseRedirect('/blog')

    return render(request,
                  'update_post.html',
                  {'update-post': post, 'form': form})


@login_required
def delete_post(request, post_id):
    """
    Users can delete post
    """
    pst = Post.objects.get(pk=post_id)
    context = {'pst': pst}

    if request.method == 'POST':
        pst.delete()
        messages.success(request,
                         ('You have deleted this review sucessfully.'))
        return redirect('blog')

    return render(request, 'delete.html', context)


@login_required
class AddPost(CreateView):
    """
    Ensures that person is logged in to create
    a blog post
    """
    template_name = 'add_post.html'
    model = Post
    form_class = CreatePost

    def form_valid(self, form):
        """_summary_
        validates the form and adds a success message
        to the template once a Post is successfully added
        Sets the automatic slug for the object created
        from the user input on the title
        field
        """
        form.instance.author = self.request.user
        messages.success(
            self.request,
            'Your blog post has now been posted')
        form.slug = slugify(form.instance.title)
        return super().form_valid(form)


def contact(request):
    """
    Submits contact us form to the admin dashboard.

    """
    submitted = False
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/contact?submitted = True')
    else:
        form = ContactForm()
        if 'submitted' in request.GET:
            submitted = True
    return render(request, 'contact.html',
                  {'form': form, 'submitted': submitted})


class Faqs(CreateView):
    """
    Displays Frequently asked questions page.
    """
    template_name = 'faqs.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})


def sustainable_leather(View):
    model = Post
    queryset = Post.objects.filter(title="What is Sustainable Leather?")
    return HttpResponseRedirect('/blog/what-is-sustainable-leather/')


def meet_the_tanner(View):
    model = Post
    queryset = Post.objects.filter(title="Meet the chief Tanner")
    return HttpResponseRedirect('/blog/meet-the-chief-tanner/')


def certs(View):
    model = Post
    queryset = Post.objects.filter(
        title="We are a Certified Sustainable leather Manufacturer.")
    return HttpResponseRedirect('/blog/we-are-a-certified/')


def custom(View):
    model = Post
    queryset = Post.objects.filter(title="Bespoke Made to Order")
    return HttpResponseRedirect('/blog/bespoke-made-to-order/')

blog/templates/add_post.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block content %}


{% block page_header %}
<div class="container header-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock %}

	<div class="container mb-3">
		<div class="row">
			<div class="col-md-8 mt-1 offset-md-2">
				<!-- Success alert when submitted -->
               <h1> {% if Posted %} You have sucessfully created a new blog post</h1>
            {% else %} 
				<h1>Add Post...</h1>
                <div class="container">
					<div class="row">
						<form method=POST enctype="multipart/form-data"> 
              {% csrf_token %} 
              {{ form|crispy }}
							<button>Post</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endif %}
{% endblock %}

blog/templates/blog.html
{% extends "base.html" %}
{% load static %}
{% load bag_tools %}


{% block page_header %}
<div class="container header-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock %}

{% block content %}
<!-- Blog Entries Column -->

  <div class="container-fluid col-10">
            {% for post in post_list %}
                <div class="col mt-3 mb-3">
                  <h1>{{ post.title }}</h1> 
                </div>
                        <div class="img-container">
                        {% if "placeholder" in post.featured_image.url %}
                            <img class="card-img-top" src="{{ post.featured_image }}" style="width:80%; height:auto"
                            alt="Blog post image">
                        {% else %}
                            <img class="card-img-top mb-3" src=" {{ post.featured_image.url }}" alt="" style="width:80%; height:auto;">
                        {% endif %}
                        </div>
                        <div class="card-body col-8">
                                <p class="card-text text-muted mb-2">{{ post.created_on}}
                                   {{ post.author }}</p>
                                <p class="card-text ml-3">{{post.snippet}}</p>
                                 <a href="{% url 'post_detail' post.slug %}" class="btn btn-dark">Read More</a>
                        </div>
                      {% if request.user.is_superuser %}
                          <small class="ml-3">
                              <a href="{% url 'update_post' post.id %}">Edit</a>
                              <a class="text-danger" href="{% url 'delete_post' post.id %}">Delete</a>
                          </small>
                      {% endif %}
                      <hr class="hr1">
                      {% endfor %}
                      <div>
                    </div>
                  </div>
                        <!-- Pagination -->
                      {% if is_paginated %}
                      <nav aria-label="Page navigation">
                          <ul class="pagination justify-content-center">
                            {% if page_obj.has_previous %}
                              <li>
                                  <a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a>
                              </li>
                            {% endif %}
                            {% if page_obj.has_next %}
                              <li>
                                  <a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a>
                              </li>
                            {% endif %}
                         </ul>
                      </nav>
         </div>
  {% endif %}
{%endblock%}
<script>

function scrollFunction() {
  if(document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
    mybutton.style.display = "block";
  } else {
    mybutton.style.display = "none";
  }
}
// When the user clicks on the button, scroll to the top of the document
function topFunction() {
  document.body.scrollTop = 0;
  document.documentElement.scrollTop = 0;
}
</script>

blog/templates/contact.html
{% extends "base.html" %} 
{% load crispy_forms_tags %} 


{% block page_header %}
<div class="container header-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock %}

{% block content %}
  <div class="container fluid">
    <div class="row">
      <!-- Section Titile -->
      <div>
        <h3 class="section-title">Contact Us</h3>
      </div>
    </div>
    <div class="row">
      <!-- Section Titile -->
      <p>Do you have a question, a concern?
        If so, please complete the form below and we will aim to respond within 24 hours.
        Also visit our<a class="mailto-anchor" href="{% url 'faqs' %}"><strong> FAQs
          page</strong></a> as you might find your question has already been answered there.</p>
    </div>
    <!-- contact form -->
    <div">
      <form id="contact-form" method="post"> {% csrf_token %} {{ form|crispy }}
        <!-- Form Submit -->
        <button id="submitForm" class="btn btn-dark mb-3">Send</button>
      </form>
    </div>
  </div>
{% endblock %}

blog/templates/delete.html
{% extends "base.html" %} 
{% load crispy_forms_tags %} 
{% block content %} 
{% if user.is_superuser %}
<div class="container mt-5 pt-5">
	<h1>Delete Post:</h1>
	<div class="row">
	    <form method="POST" action={% url 'delete_post' pst.id %} class="ui form"> {% csrf_token %} {{ form|crispy }}
		<p>Are you sure you want to delete this review?</p>
		<input type="submit" value="YES" class="btn btn-danger">
		<a href="{% url 'blog' %}" class="btn btn-dark">Cancel</a>
	  </form>
	</div>
  </div> 

  {% else %}   
  <h1>Please login.</h1>
{% endif %}

{% endblock %}

blog/templates/post_details.html
{% extends 'base.html' %} 
{% block content %}
{% load crispy_forms_tags %}

{% block page_header %}
<div class="container header-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock %}

<div class="masthead offset-md-1">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                 <h1 class="post-title">{{ post.title }}</h1>
                 <div class="card-text">
                    {{ post.content | safe }}
                 </div>
             </div>
             <div class="d-none d-md-block col-md-5 masthead-image">
                 <!-- The featured image URL or an alternitive if one isnt provided -->
                 <div class="image-container">
                    {% if "placeholder" in post.featured_image.url %}
                    <img class="card-img-top" src="{{ post.featured_image }}" style="width:100%"
                      alt="Blog post image">
                    {% else %}
                    <img class="card-img-top" src=" {{ post.featured_image.url }}" alt="" style="width:100%">
                    {% endif %}
                  </div>
            <p class="post-subtitle">Author: {{ post.author }} | {{ post.created_on }}</p>
        </div>
        </div>

        {% if request.user.is_superuser %}
        <small class="ml-3">
            <a href="{% url 'update_post' post.id %}">Edit</a>
            <a class="text-danger" href="{% url 'delete_post' post.id %}">Delete</a>
        </small>
        <a class="btn btn-dark mb-4" href="{% url 'blog' %}">Back </a>
{% else %}
<a class="btn btn-dark mb-4" href="{% url 'blog' %}">Back </a>
</div>
</div>

{% endif %} 


{% endblock content %}

blog/templates/update_post.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}


{% block page_header %}
<div class="container header-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock %}

{% if user.is_superuser %} 
<div class="container">
    <h1>Edit the Blog Post:</h1>
    <div class="row">
      <div class="col-md-8 mt-3 offset-md-2 mb-2">
        <form method=POST> {% csrf_token %} {{ form|crispy }}
          <br>
          <input type="submit" value="Update" class="btn btn-dark">
          <a class="btn btn-dark" href="{% url 'blog' %}">Back </a>
        </form>       
      </div>
    </div>
    {% else %}  
    <div class="ml-5">
        <h3>This is not your Post.</h3> 
        <p>Only the Post Author can amend this blog post.</p>
            <a class="btn btn-dark" href="{% url 'blog' %}">Back </a>
    </div>
</div> 
{% endif %}

{% endblock %}