bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.shopping_bag, name='shopping_bag'),
    path('add/<item_id>/', views.add_item, name='add_item'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_item, name='remove_item'),
]

leather_works/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('blog/', include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'leather_works.views.handler404'

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('add', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/',
         views.delete_product, name='delete_product'),
]

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings

from django_countries.fields import CountryField

from products.models import Product
from profiles.models import UserProfile


class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                     null=True,
                                     blank=True, related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label="Country *", null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(
                                        max_digits=6, decimal_places=2,
                                        null=False, default=0)
    order_total = models.DecimalField(
                                        max_digits=10, decimal_places=2,
                                        null=False, default=0)
    grand_total = models.DecimalField(
                                        max_digits=10, decimal_places=2,
                                        null=False, default=0)
    original_bag = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(
                                    max_length=254, null=False,
                                    blank=False, default='')

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line item is added,
        accounting for delivery costs.
        """
        self.order_total = self.lineitems.aggregate(
            Sum('lineitem_total'))['lineitem_total__sum'] or 0
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = \
                self.order_total * settings. STANDARD_DELIVERY_PERCENTAGE / 100
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(Order, null=False,
                              blank=False, on_delete=models.CASCADE,
                              related_name='lineitems')
    product = models.ForeignKey(Product, null=False,
                                blank=False, on_delete=models.CASCADE)
    product_color = models.CharField(max_length=6,
                                     null=True, blank=True)  # Tan rust black
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(max_digits=6, decimal_places=2,
                                         null=False, blank=False,
                                         editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.db.models import Avg
from django.core.validators import MaxValueValidator,MinValueValidator

class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categoies'
        
    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name
    


class Product(models.Model):
    category = models.ForeignKey('Category', null=True, blank=True, on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    color_choice = models.BooleanField(default=False, null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image_url_2 = models.URLField(max_length=1024, null=True, blank=True)
    image_url_3 = models.URLField(max_length=1024, null=True, blank=True)
    thumbnail_url = models.URLField(max_length=1024, null=True, blank=True)
    thumbnail = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name


    
class Review(models.Model):
    """
    Models the fields for adding product reviews.
    """
    User = get_user_model()
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='reviews'
    )
    username = models.ForeignKey(User, on_delete=models.CASCADE,
                                 related_name='user_reviews')
    message = models.TextField(help_text='Add your review here')
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return f'Review {self.message} by {self.username}'

products/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import Product, Category, Review

class NewProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    
    def __init__(self, *args, **Kwargs):
        super().__init__(*args, **Kwargs)
        categories = Category.objects.all()
        firendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = firendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-0'


class ReviewForm(forms.ModelForm):
    """
    Uses Django form to enable users
    to add product reviews within
    Post Detail view.
    """
    class Meta:
        model = Review
        fields = ('message',)

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.views.generic import DeleteView
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower
from .models import Product, Category, Review
from .forms import NewProductForm, ReviewForm

# Create your views here.

def all_products(request):
    """ A view to show all products, including sorting and search queries """

    products = Product.objects.all()
    query = None
    categories = None
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if sortkey == 'category':
                sortkey = 'category__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)
             

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, "You didn't enter any search criteria!")
                return redirect(reverse('products'))
            
            queries = Q(name__icontains=query) | Q(description__icontains=query)
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'    

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
    }

    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """ A view to show individual product details """
 
    
    # Return the requested product or 404
    product = get_object_or_404(Product, pk=product_id)
    reviews = product.reviews.order_by('-created_on')
    

    if request.user.is_authenticated:
        review_form = ReviewForm(data=request.POST)

        if review_form.is_valid():
            review_form.instance.username = request.user
            review = review_form.save(commit=False)
            review.product = product
            review.save()
            messages.success(request, 'Thank you for taking \
                the time to provide a review')

    # Context to return to the page
    context = {
        'product': product,
        'reviews': reviews,
        'reviewed': False,
        'review_form': ReviewForm(),
    }
    return render(request, 'products/product_detail.html', context)


@login_required
def add_product(request):
    """ Add a new product to a store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = NewProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully added product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to add product. Please ensure the form is valid.')
    else:
        form = NewProductForm()
    template = 'products/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """ Edit a product on website """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = NewProductForm(request.POST, request.FILES, isinstance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to update product. Please ensure the form is valid before submitting.')
    else:
        form = NewProductForm(instance=product)

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """ Delete a product from the front end """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only the owners can do that.')
        return redirect(reverse('products'))

    product = get_object_or_404(Product, pk=product_id)

    if request.method == 'POST':
        product.delete()
        messages.success(request, f'{product.name} successfully deleted.')
        return redirect(reverse('products'))

    return render(request, 'products/confirm_delete.html')
        

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %} 

{% block head_title %}- Add a product {% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'base.css' %}">
{% endblock %}

{% block content %}
{% block page_header %}
<div class="container header-container mt-5 pt-3">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock %}


<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-md-6">
        <h2 class="logo-font mb-4">Add a Product</h2>
        <br>
    </div>
</div>
<div class="row">
    <div class="col-12 col-md-6 mb-4">
        <form method="POST" action="{% url 'add_product' %}" class="form mb-2" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                {% if field.name != 'thumbnail' %}
                   {{ field | as_crispy_field }}
                {% else %}
                   {{ field }}
               {% endif %}
            {% endfor %}
            <div class ="text-right">
                <a class="btn btn-dark rounded-0" href="{% url 'products' %}">Cancel</a>
                <button class="btn btn-dark rounded-0" type="submit">Add Product</button>
            </div>
        </form>
    </div>
</div>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
<script type="text/javascript">
$('#new-image').change(function() {
    var file = $('#new-image')[0].files[0];
    $('#filename').text(`Image will be set to: ${file.name}`);
});
</script>
{% endblock %}

products/templates/products/confirm_delete.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}{% trans 'Delete Product' %}{% endblock %}



{% block content %}
<!-- User must be authenticated to view these page and perform actions -->
{% if request.user.is_superuser %}
             
<!-- Page header -->
<div class="container-fluid">
    <div class="row">
        <div class="col text-center mt-3 pt-5 mb-3">
            <hr class="w-50 mb-1">
        </div>
    </div>
    <!-- Container for Deleting a product -->
    <div class="row">
        <div class="col-md-8 mt-3 pt-5 offset-md-2">
            <div class="card-body">
                <h2 class="page-subtitle mb-3">Are you sure you would like to delete this product?</h2>
                <!-- Confirming the product identified for deletion -->
            </div>
        </div>
    </div>
    <!-- Container for delete form -->
    <div class="row">
        <div class="col-md-8 mt-3 offset-md-2">
            <div class="card-body">
                <!-- Form used to perform the action with the database -->
                <form method="POST">
                    <div class="form-group">
                        <div class="input-group">
                            {% csrf_token %}
                            <!-- Option to cancel if navigated to in error -->
							
                            <a href="{% url 'products' %}" class="btn rounded-0 btn-dark m-1">Cancel</a>
                            <!-- Button to delete the product from the database -->
                            <input class="btn rounded-0 btn-danger m-1" type="submit" value="Delete">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% else %}
<!-- Information to user if navigated to in error without being signed in -->
<div class="container fluid">
    <div class="row justify-content-center">
        <div class="card-block">
            <p class="card-text">
                Sorry you must be signed in to access this page, use the button below to
                return to our homepage
            </p>
            <a href="{% url 'home' %}" class="btn rounded-0 btn-muted">Home
            </a>
        </div>
    </div>
</div>
{% endif %}

{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}{% trans 'Edit Product' %}{% endblock %}

{% block extra_css %}

{% endblock %}

{% block content %}
<!-- Page header -->
<div class="container-fluid">
    <div class="row">
        <div class="col text-center mt-3 mb-3">
            <hr class="w-50 mb-1">
        </div>
    </div>
    <!-- Container for Edit Product form -->
    <div class="row">
        <div class="col-12 col-md-6 mb-4">
            <h2 class="page-subtitle mb-3">Edit Product</h2>
            <form action="{% url 'edit_product' product.id %}" class="form mb-2" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    {% if field.name != 'thumbnail' %}
                        {{ field | as_crispy_field }}
                    {% else %}
                        {{ field }}
                    {% endif %}
                {% endfor %}
                <div class="text-left">
                    <!-- Cancel button -->
                    <a href="{% url 'products' %}" class="btn rounded-0 btn-dark mt-3">Cancel</a>
                    <!-- Submit button -->
                    <button class="btn rounded-0 btn-dark mt-3" type="submit">Submit Updates</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
<script>
    $('#new-image').change(function () {
        var file = $('#new-image')[0].files[0];
        $('#filename').text(`Image will be set to: ${file.name}`);
    });
</script>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block head_title %}- Product details {% endblock %}

{% block page_header %}
    <div class="container header-container-prod">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
        {% endblock %}

        {% block content %}

        <div class="overlay"></div>
            <div class="container-fluid">
                <div>
                    <div class="image-container">
                        <div>      
                        {% if product.thumbnail %}
                            <!-- The grid: four columns -->
                            <div class="container-img2">
                                <div class="row mt-md-5 mt-sm-3 mt-lg-3 mb-md-1">
                                    <div class="column">
                                        <img src="{{ product.thumbnail.url }}" alt="{{ product.name }}" style="width:100%;" onclick="myFunction(this);">
                                    </div>
                                    <div class="column">
                                        <img src="{{ product.image_url }}" alt="{{ product.name }}" style="width:100%;" onclick="myFunction(this);">
                                    </div>
                                    <div class="column">
                                        <img src="{{ product.image_url_2 }}" alt="{{ product.name }}" style="width:100%;" onclick="myFunction(this);">
                                    </div>
                                    <div class="column">
                                        <img src="{{ product.image_url_3 }}" alt="{{ product.name }}" style="width:100%;" onclick="myFunction(this);">
                                    </div>
                                </div>
                                <div class="container-img1">
                                   <span onclick="this.parentElement.style.display='none'" class="closebtn">&times;</span>
                                       <img id="expandedImg" style="width:100%">
                                       <div id="imgtext"></div>
                             </div>
                                <div id="thumbnail">
                                    <img src="{{ product.thumbnail.url }}" alt="{{ product.name }}" style="width:100%;">
                                </div>
                                {% else %}
                                     <img src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="product-details-container mb-5 mt-md-5">
                            <h3 class="mb-0">{{ product.name }}</h3>
                                <p class="lead mb-0 text-left font-weight-bold">${{ product.price }}</p>
                                {% if product.category %}
                                <p class="small mt-1 mb-0">
                                    <a class="text-muted" href="{% url 'products' %}?category={{ product.category.name }}">
                                       <i class="fas fa-tag mr-1"></i>{{ product.category.friendly_name }}
                                    </a>
                                </p>
                                {% endif %}
                                {% if request.user.is_superuser %}
                                <small class="ml-3">
                                    <a href="{% url 'edit_product' product.id %}">Edit</a>
                                    <a class="text-danger" href="{% url 'delete_product' product.id %}">Delete</a>
                                </small>
                                {% endif %}
                                <p class="mt-3">{{ product.description }}</p>
                                <form class ="form" action="{% url 'add_item' product.id %}" method="POST">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        {% with product.color_choice as c %}
                                        {% if c %}
                                        <div class="col-12">
                                            <p><strong>Colour leather:</strong></p>
                                            <select class ="form-control rounded-0 w-50" name="product_color" id="id_product_color">
                                                <option value="tan" selected>Tan</option>
                                                <option value="rust">Rust</option>
                                                <option value="black">Black</option>
                                            </select>
                                        </div>
                                        {% endif %}
                                        <div class="col-12">
                                            <p class="mt-3"><strong>Quantity:</strong></p>
                                                <div class="form-group w-50">
                                                    <div class="input-group input_group_{{ prodcut.id }}">
                                                        <div class="input-group-prepend">
                                                            <button class="decrement-qty btn brn-muted rounded-0 decrement-qty_{{ product.id }}" 
                                                                data-item_id="{{ product.id }}">
                                                                <span>
                                                                    <i class="fas fa-minus fa-sm"></i>
                                                                </span>
                                                            </button>
                                                        </div>
                                                        <input class="form-control qty_input id_qty_{{ product.id }}" type="number"
                                                            name="quantity" value="1" min="1" max="99" data-item_id="{{ product.id }}">
                                                            <div class="input-group-append">
                                                                <button class="increment-qty btn btn-muted rounded-0 increment-qty_{{ product.id }}"
                                                                    data-item_id="{{ product.id }}">
                                                                    <span>
                                                                       <i class="fas fa-plus fa-sm"></i>
                                                                    </span>
                                                                </button>
                                                            </div>
                                                    </div>
                                                </div>
                                        </div>
                                    </div>
                                        <div class="col{% if c %}-12 mt-2{% endif %}">
                                            <a href="{% url 'products' %}" class="btn btn-outline-black rounded-0 mt-5">
                                                <span class="icon">
                                                    <i class="fas fa-chevron-left"></i>
                                                </span>
                                                <span class="text-uppercase">Keep Shopping</span>
                                             </a>
                                            <input type="submit" class="btn rounded-0 text-uppercase mt-5" value="Add item">
                                        </div>
                                        <input type="hidden" name="redirect_url" value="{{ request.path }}">
                                        {% endwith %}
                                </form>
                        </div>
                </div>
             <!--- Container for product reviews -->
                <div class="mb-5 pb-5">
                    <div class="container-fluid mt-2 mb-5">
                       <div class="row">
            <!--- Container for product reviews -->
                            <div class=" card mb-4 mt-3 border border-warning p-3">
                                <div class="card-body mb-3">
                                    <h3 class="card-subtitle mb-2 cust-review-h3" style="color: #cb9b51">Customer Reviews</h3>
                                       {% for review in reviews %}
                                    <p class="card-text">Review left by: {{ review.username }}</p>
                                    <p class="card-text"><i>
                                    {{ review.message | linebreaks }}</i></p>
                                        <span class="text-muted">
                                            {{ review.created_on }}
                                        </span>
                                </div>
                                    {% endfor %}
                            </div>
                                <!-- Container for adding product reviews -->
                            <div class="card-body mb-4">
                                <!--- Link to inform how registration is required -->
                                {% if not user.is_authenticated %}
                                <div class="card-body">
                                   <h3 class="card-subtitle mb-2" style="color:  #cb9b51">Would you like to review this product?</h3>
                                    <div class="card-body mb-3">
                                        <p class="card-text register-text">Please either <a style="color: #cb9b51"
                                            href="{% url 'account_login' %}"><strong>sign in</strong></a> to your account or register first.
                                        </p>
                                        <div><a href="{% url 'account_signup' %}" class="btn btn-dark">Sign Up</a></div>
                                    </div>
                                    <!--- Signed in user can leave a product review -->
                                    {% else %} {% if user.is_authenticated %}
                                    <h3 class="card-subtitle cust-review-h3" style="color: #cb9b51">Leave your review</h3>
                                    <p class="card-text">
                                        Reviewing as:
                                        <span>{{ user.username }}</span>
                                    </p>
                                    <!---User feature to add product review  -->
                                        <form method="post" style="margin-top: 1.3em;">
                                            {{ review_form | crispy }} {% csrf_token %}
                                            <!---Button to submit product review -->
                                            <button type="submit" class="btn btn-dark mb-5">Submit</button>
                                        </form>
                                </div>
                            </div>
                            {% endif %} {% endif %}
                        </div>
                    </div>
                    </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}
{% endblock %}